[package]
name = "pop-launcher-plugin-duckduckgo-bangs"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
serde = "1"
serde_json = "1.0"
pop-launcher = "1.0.1"
futures-lite = "1"
urlencoding = "2"

[[bin]]
name = "bangs"
path = "src/main.rs"
